### ISSUE TITLE
Feature Request: Kali Replacement

### ISSUE THREAD

**Issue by Danfun64** [fragglet/ipxbox#1]
I think it would be cool if you wrote a free open source ipx though tcp/ip tunneling client for dos that allowed real dos machines to connect to dosbox ipxnet servers through the internet, much like what Kali did back in the day. Maybe even give the ability for real DOS machines to host ipxnet compatible servers for good measure. Granted, it would probably be a project in itself, and I'm not sure how much code (if any) can be reused from this, but it would definitely make DOS LANs easier.

**Comment by fragglet** [comment]
It's a nice idea but it's out of scope for this project.

What you probably actually want is one of:

- A Windows 9x network driver that pretends to be a network card but actually tunnels over TCP/IP (what Kali did, I assume)
- Something equivalent using a DOS network stack. For example, a Novell ODI driver that pretends to be a network card but is a tunnel. Or a TSR driver that implements the IPX ODI API but tunnels over a DOS network stack - take your pick from the Novell API, Trumpet, WATTCP or others. In recent years [mTCP](http://www.brutman.com/mTCP/) has become quite popular as an open source DOS TCP/IP stack, so it would probably make a nice addition to that project.

**Comment by fragglet** [comment]
Note that I'm declaring it as out of scope to mean "I'm personally not going to work on this". I don't have a real DOS machine I could even use to develop it. But if you or someone else would like to work on it then I'm happy to accept such a contribution - it could be nice to start collecting different DOSbox UDP-related tools under one umbrella and I'm happy to collaborate.
