### ISSUE TITLE
PPTP - TCP/IP support?

### ISSUE THREAD

**Issue by skadarnold** [fragglet/ipxbox#14]
Is TCP/IP protocol with a focus on support for LAN TCP gaming over PPTP possible?

**Comment by fragglet** [comment]
Interpreting the question to mean: "Would you be open to extending the PPTP server to support tunneling TCP/IP as well as IPX?". If that's not what you mean then please say.

I think I'd like to declare it out of scope, at least for the time being. The focus of the project is on IPX gaming, other VPN systems already exist for tunneling TCP/IP, and the goal here is to connect things up with the DOSbox protocol, which only transports IPX, not TCP/IP.
