### ISSUE TITLE
NFS 2 SE and NFS 3 network game

### ISSUE THREAD

**Issue by shikoist** [fragglet/ipxbox#19]
Can't see or join other session in NFS. Diablo, Star Wars Racer, IPX Local Chat are working on IPX, can see games, join and play.

**Comment by shikoist** [comment]
No, there are two retroPC with Windows 98 SE and NFS 2 SE (two cities, 3500 km distance), actually. In the meantime, I can't see  or join even in my LAN, so this is not ipxbox issue. Sorry for the false alarm.

**Comment by fragglet** [comment]
Just as a note for future reports: please try to provide as much information as possible about your setup otherwise it's hard to debug what's happening.
