### ISSUE TITLE
ipxbox in Termux

### ISSUE THREAD

**Issue by MaxWell-775** [fragglet/ipxbox#28]
Hello, I need help. I have successfully compiled ipxbox in Termux and launched it as instructed. 
I opened DosBox Turbo on Android and entered the following command:

`ipxnet connect localhost 10000`

DosBox Turbo displayed the following:

`IPX Tunneling utility for DosBox
IPX Tunneling Client connected to server at localhost.`

I started the IPX packet driver with the command ipxpkt 0x60, and then tried to open the http://example.com website in the elinks browser, but it gave an error:

`Unable to retrieve http://example.com/
Host not found`

![Screenshot_20230806-042037423.jpg](https://github.com/fragglet/ipxbox/assets/75186533/ab8fca33-50d5-4206-9b8c-afcf045402d4)

![Screenshot_20230806-042158791.jpg](https://github.com/fragglet/ipxbox/assets/75186533/5565327d-42a1-4886-9812-9ee6e516db3a)

![Screenshot_20230806-042232652.jpg](https://github.com/fragglet/ipxbox/assets/75186533/15dfff4d-b441-41c4-ae14-0a300b4717a7)

![Screenshot_20230806-042339038.jpg](https://github.com/fragglet/ipxbox/assets/75186533/cf7682ce-4a86-4355-8d96-7fda6e43e412)

**Comment by fragglet** [comment]
Hi, can you give some context about what you're trying to do and why you think ipxbox is the right solution?

https://xyproblem.info/

**Comment by Offliner33** [comment]
They are trying to get internet access in Dosbox through ipxbox. In this case they are running ipxbox in Android. What they want to do does not work on Android without having a rooted device.

**Comment by fragglet** [comment]
I'd like to hear the reporter describe things in their own words, though I suspect your answer is probably correct.

Given lack of reply in two weeks I'm going to close the bug but if you want to provide more information we can reopen it and have that discussion
