### ISSUE TITLE
No code license declared

### ISSUE THREAD

**Issue by sskras** [fragglet/ipxbox#4]
By having it, it would be easier for those trying to use the code in other projects or port it to other platforms/languages.

Personally I would suggest using some kind of permissive F/LOSS license having protection against patent trolls.

Like Apache License 2.0 or, if you would like a lot plainer legal language, the new [Blue Oak Model License 1.0.0](https://heathermeeker.com/2019/03/07/blue-oak-council-and-the-permissive-license-list/).

YMMV:)

**Comment by fragglet** [comment]
What a foolish oversight on my part. Thanks for the report, and fixed in 39b474b643d0fd47e7a629e910a9e9612d0ff630
