### ISSUE TITLE
Native DOS

### ISSUE THREAD

**Issue by cyberluke** [fragglet/ipxbox#6]
Hi, if I setup this with libpcap on Raspberry Pi, can I use native DOS game and DOSBox game together?

The next step: If I run public server and clients have internet access, can this tunnel work seamlessly for both native DOS and DosBox clients to play together?

If not, is there something I could develop as software developer?

**Comment by fragglet** [comment]
Yes, I have a Raspberry Pi set up in my own home doing exactly this.

**Comment by cyberluke** [comment]
Hi, perfect. Can you please give me some hint what kind of setup I need?
OpenVpn?

**Comment by fragglet** [comment]
https://github.com/fragglet/ipxbox/blob/master/HOWTO.md#advanced-topic-setting-up-an-ipx-network-bridge
